<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Icon Voucher Category</name>
   <tag></tag>
   <elementGuidId>a5753a01-42cc-46b2-9e5f-533c3bb2e727</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <katalonVersion>7.7.2</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>${BaseFlick-Staging}/v1/users/${userId}}/voucher/kategori/${kategoriId}/icon</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.BaseFlick-Staging</defaultValue>
      <description></description>
      <id>5dd083f7-5947-457a-956a-e82ad24cb1b9</id>
      <masked>false</masked>
      <name>BaseFlick-Staging</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.userId}</defaultValue>
      <description></description>
      <id>8e109c9e-cee3-4237-8639-cfdcbc9939dd</id>
      <masked>false</masked>
      <name>userId}</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.kategoriId</defaultValue>
      <description></description>
      <id>04245961-8623-4faa-a76e-c7d89c723f06</id>
      <masked>false</masked>
      <name>kategoriId</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
