<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Image</name>
   <tag></tag>
   <elementGuidId>0778ee50-3979-4365-a225-4df10517c5d7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <katalonVersion>7.7.2</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>${Silvi-Staging}/static/assets/${image_category}/${filename}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.Silvi-Staging</defaultValue>
      <description></description>
      <id>c38acc10-af5e-4394-8ab2-3a51a796245d</id>
      <masked>false</masked>
      <name>Silvi-Staging</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.image_category</defaultValue>
      <description></description>
      <id>64ac71bd-1cc3-4d76-86d9-37f7104d8623</id>
      <masked>false</masked>
      <name>image_category</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.filename</defaultValue>
      <description></description>
      <id>cbdfa075-2ec2-4640-ae05-3bd53b2384b9</id>
      <masked>false</masked>
      <name>filename</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
