<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Get Image</name>
   <tag></tag>
   <elementGuidId>86b81a5e-dfe0-423d-b36e-36ffd8e0fc5e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <katalonVersion>7.7.2</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>/static/assets/${image_category}/${filename}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.image_category</defaultValue>
      <description></description>
      <id>b9eeb1e1-c342-45dc-8882-65e977379be4</id>
      <masked>false</masked>
      <name>image_category</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.filename</defaultValue>
      <description></description>
      <id>ac276598-1858-4d6c-a15f-2d87a6642996</id>
      <masked>false</masked>
      <name>filename</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
